
import React, { useState, useMemo } from 'react';
import { User, Group, Role } from '../types';
import Modal from './Modal';
import { EditIcon, TrashIcon, PlusCircleIcon, EyeIcon, EyeOffIcon } from './Icons';
import { useLanguage } from '../lib/LanguageContext';

interface TutorsProps {
    users: User[];
    groups: Group[];
    onCreate: (data: { firstName: string; lastName: string; username?: string; password?: string }) => void;
    onUpdate: (id: string, data: { firstName: string; lastName: string; username?: string; password?: string }) => void;
    onDelete: (id: string) => void;
}

const TutorForm: React.FC<{
    tutor: Partial<User> | null;
    onSave: (data: { firstName: string; lastName: string; username?: string; password?: string }) => void;
    onCancel: () => void;
}> = ({ tutor, onSave, onCancel }) => {
    const { t } = useLanguage();
    const [firstName, setFirstName] = useState(tutor?.firstName || '');
    const [lastName, setLastName] = useState(tutor?.lastName || '');
    const [username, setUsername] = useState(tutor?.username || '');
    const [password, setPassword] = useState('');

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        onSave({ firstName, lastName, ...(username && { username }), ...(password && { password }) });
    };

    return (
        <form onSubmit={handleSubmit} className="space-y-4">
            <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
                <div>
                    <label htmlFor="firstName" className="block text-sm font-medium text-gray-700">{t('name')}</label>
                    <input
                        type="text"
                        id="firstName"
                        value={firstName}
                        onChange={(e) => setFirstName(e.target.value)}
                        className="w-full p-2 mt-1 border border-gray-300 rounded-md"
                        required
                    />
                </div>
                <div>
                    <label htmlFor="lastName" className="block text-sm font-medium text-gray-700">{t('surname')}</label>
                    <input
                        type="text"
                        id="lastName"
                        value={lastName}
                        onChange={(e) => setLastName(e.target.value)}
                        className="w-full p-2 mt-1 border border-gray-300 rounded-md"
                        required
                    />
                </div>
            </div>
            <div>
                <label htmlFor="tutorUsername" className="block text-sm font-medium text-gray-700">{t('usernameOptional')}</label>
                <input
                    type="text"
                    id="tutorUsername"
                    value={username}
                    onChange={(e) => setUsername(e.target.value)}
                    className="w-full p-2 mt-1 border border-gray-300 rounded-md"
                    placeholder={t('autoGeneratedIfBlank')}
                />
            </div>
            <div>
                <label htmlFor="password" className="block text-sm font-medium text-gray-700">
                    {tutor ? t('newPasswordOptional') : t('password')}
                </label>
                <input
                    type="password"
                    id="password"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    className="w-full p-2 mt-1 border border-gray-300 rounded-md"
                    placeholder={tutor ? t('leaveBlankNoChange') : ''}
                    required={!tutor}
                />
            </div>
            <div className="flex justify-end pt-4 space-x-2">
                <button type="button" onClick={onCancel} className="px-4 py-2 text-gray-700 bg-gray-100 rounded-md hover:bg-gray-200">{t('cancel')}</button>
                <button type="submit" className="px-4 py-2 text-white bg-green-600 rounded-md hover:bg-green-700">{t('save')}</button>
            </div>
        </form>
    );
};

const Tutors: React.FC<TutorsProps> = ({ users, groups, onCreate, onUpdate, onDelete }) => {
    const { t, language } = useLanguage();
    const [isModalOpen, setIsModalOpen] = useState(false);
    const [editingTutor, setEditingTutor] = useState<User | null>(null);
    const [tutorToDelete, setTutorToDelete] = useState<User | null>(null);
    const [visiblePasswords, setVisiblePasswords] = useState<Record<string, boolean>>({});
    const [visibleUsernames, setVisibleUsernames] = useState<Record<string, boolean>>({});

    const tutors = useMemo(() => {
        return users
            .filter(u => u.role === Role.Tutor)
            .sort((a, b) => a.lastName.toLowerCase().localeCompare(b.lastName.toLowerCase(), language === 'es' ? 'es' : 'en'));
    }, [users, language]);

    const togglePasswordVisibility = (id: string) => {
        setVisiblePasswords(prev => ({ ...prev, [id]: !prev[id] }));
    };

    const toggleUsernameVisibility = (id: string) => {
        setVisibleUsernames(prev => ({ ...prev, [id]: !prev[id] }));
    };

    const handleCreate = () => {
        setEditingTutor(null);
        setIsModalOpen(true);
    };

    const handleEdit = (tutor: User) => {
        setEditingTutor(tutor);
        setIsModalOpen(true);
    };

    const handleDeleteClick = (tutor: User) => {
        setTutorToDelete(tutor);
    };

    const handleConfirmDelete = () => {
        if (tutorToDelete) {
            onDelete(tutorToDelete.id);
            setTutorToDelete(null);
        }
    };

    const handleSave = (tutorData: { firstName: string; lastName: string; username?: string; password?: string }) => {
        if (editingTutor) {
            onUpdate(editingTutor.id, tutorData);
        } else {
            onCreate(tutorData);
        }
        setIsModalOpen(false);
        setEditingTutor(null);
    };
    
    const assignedGroupsCount = (tutorId: string) => {
        return groups.filter(g => g.tutorId === tutorId).length;
    };

    return (
        <div className="p-4 bg-white rounded-lg shadow-md">
            <div className="flex flex-wrap items-center justify-between gap-4 mb-6">
                 <div></div>
                 <button onClick={handleCreate} className="flex items-center gap-2 px-4 py-2 font-semibold text-white bg-green-600 rounded-md hover:bg-green-700">
                    <PlusCircleIcon className="w-5 h-5" />
                    {t('addTutor')}
                </button>
            </div>

            <div className="overflow-x-auto">
                <table className="w-full text-left table-auto">
                    <thead className="bg-gray-50">
                        <tr>
                            <th className="px-4 py-3 font-semibold text-gray-600">{t('name')}</th>
                            <th className="px-4 py-3 font-semibold text-gray-600">{t('username')}</th>
                            <th className="px-4 py-3 font-semibold text-gray-600">{t('password')}</th>
                            <th className="px-4 py-3 font-semibold text-gray-600">{t('assignedGroups')}</th>
                            <th className="px-4 py-3 font-semibold text-gray-600">{t('actions')}</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-200">
                        {tutors.map(tutor => (
                            <tr key={tutor.id} className="hover:bg-gray-50">
                                <td className="px-4 py-3 font-medium text-green-800">{tutor.lastName}, {tutor.firstName}</td>
                                <td className="px-4 py-3">
                                    <div className="flex items-center space-x-2">
                                        <span className="text-gray-600 font-mono">
                                            {visibleUsernames[tutor.id] ? tutor.username : '••••••••'}
                                        </span>
                                        <button onClick={() => toggleUsernameVisibility(tutor.id)} className="text-gray-500 hover:text-gray-700">
                                            {visibleUsernames[tutor.id] ? <EyeOffIcon className="w-5 h-5"/> : <EyeIcon className="w-5 h-5"/>}
                                        </button>
                                    </div>
                                </td>
                                <td className="px-4 py-3">
                                    <div className="flex items-center space-x-2">
                                        <span className="text-gray-600 font-mono">
                                            {visiblePasswords[tutor.id] ? tutor.password : '••••••••'}
                                        </span>
                                        <button onClick={() => togglePasswordVisibility(tutor.id)} className="text-gray-500 hover:text-gray-700">
                                            {visiblePasswords[tutor.id] ? <EyeOffIcon className="w-5 h-5"/> : <EyeIcon className="w-5 h-5"/>}
                                        </button>
                                    </div>
                                </td>
                                <td className={`px-4 py-3 font-medium ${assignedGroupsCount(tutor.id) === 0 ? 'text-red-600' : 'text-green-800'}`}>
                                    {assignedGroupsCount(tutor.id)}
                                </td>
                                <td className="px-4 py-3">
                                    <div className="flex space-x-4">
                                        <button onClick={() => handleEdit(tutor)} className="text-blue-500 hover:text-blue-700">
                                            <EditIcon className="w-5 h-5 text-blue-500"/>
                                        </button>
                                        <button onClick={() => handleDeleteClick(tutor)} className="text-red-500 hover:text-red-700">
                                            <TrashIcon className="w-5 h-5 text-red-500"/>
                                        </button>
                                    </div>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>

            {isModalOpen && (
                <Modal title={editingTutor ? t('editTutor') : t('addTutor')} onClose={() => setIsModalOpen(false)}>
                    <TutorForm
                        tutor={editingTutor}
                        onSave={handleSave}
                        onCancel={() => setIsModalOpen(false)}
                    />
                </Modal>
            )}

            {tutorToDelete && (
                <Modal title={t('confirmDelete')} onClose={() => setTutorToDelete(null)}>
                    <div className="text-center">
                        <p className="text-lg text-gray-700">{t('deleteStudentConfirm')}</p>
                        <p className="my-2 text-xl font-bold text-red-600">"{tutorToDelete.firstName} {tutorToDelete.lastName}"</p>
                        {assignedGroupsCount(tutorToDelete.id) > 0 &&
                            <p className="text-sm text-yellow-700 bg-yellow-100 p-2 rounded-md">
                                {t('tutorAssignedToGroupsWarning', { count: assignedGroupsCount(tutorToDelete.id) })}
                            </p>
                        }
                        <div className="flex justify-center mt-6 space-x-4">
                            <button onClick={() => setTutorToDelete(null)} className="px-6 py-2 text-gray-700 bg-gray-100 rounded-md hover:bg-gray-200">
                                {t('cancel')}
                            </button>
                            <button onClick={handleConfirmDelete} className="px-6 py-2 text-white bg-red-600 rounded-md hover:bg-red-700">
                                {t('yesDelete')}
                            </button>
                        </div>
                    </div>
                </Modal>
            )}
        </div>
    );
};

export default Tutors;